[CmdletBinding()]
param(
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$sourceRoot = 'D:\QMT\local-data-lake'
$researchRoot = Join-Path $repoRoot 'research'
$targetRoot = Join-Path $researchRoot 'data-lake'

if (-not (Test-Path -LiteralPath $sourceRoot)) { throw "Research source is missing: $sourceRoot" }
if (-not (Test-Path -LiteralPath (Join-Path $repoRoot '.git'))) { throw "Not a Git repository: $repoRoot" }

$branch = (git -C $repoRoot branch --show-current).Trim()
if ($branch -ne 'research') { throw "Refusing to sync on branch '$branch'; switch to 'research' first." }

if ($DryRun) {
    robocopy $sourceRoot $targetRoot /L /MIR /XD __pycache__ .pytest_cache .venv /XF *.pyc *.pyo *.log *.db *.sqlite *.sqlite3 | Out-Null
} else {
    robocopy $sourceRoot $targetRoot /MIR /XD __pycache__ .pytest_cache .venv /XF *.pyc *.pyo *.log *.db *.sqlite *.sqlite3 | Out-Null
}
if ($LASTEXITCODE -gt 7) { throw "Research copy failed (robocopy exit code $LASTEXITCODE)." }

$sourceFiles = @(Get-ChildItem -LiteralPath $sourceRoot -File -Recurse | Where-Object {
    $_.Extension -notin '.pyc', '.pyo', '.log', '.db', '.sqlite', '.sqlite3' -and $_.FullName -notmatch '\\(__pycache__|.pytest_cache|.venv)\\'
})
$latestSource = ($sourceFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1).LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss K')

git -C $repoRoot fetch --quiet upstream
if ($LASTEXITCODE -ne 0) { throw 'Fetching upstream failed.' }
$divergence = @((git -C $repoRoot rev-list --left-right --count origin/main...upstream/main).Trim() -split '\s+')
if ($divergence.Count -ne 2) { throw 'Unable to determine fork/upstream divergence.' }
$forkOnly = $divergence[0]
$upstreamOnly = $divergence[1]
$upstreamCommits = @(git -C $repoRoot log --oneline --max-count 20 origin/main..upstream/main)
$forkCommits = @(git -C $repoRoot log --oneline --max-count 20 upstream/main..origin/main)
if ($upstreamCommits.Count -eq 0) { $upstreamCommits = @('(none)') }
if ($forkCommits.Count -eq 0) { $forkCommits = @('(none)') }
$changed = @(git -C $repoRoot status --short -- research)
$statusBlock = @"
<!-- sync-status:start -->
## Sync status

- Tracked source files: $($sourceFiles.Count)
- Latest local source modification: $latestSource
- Fork main commits not in upstream: $forkOnly
- Upstream main commits awaiting review: $upstreamOnly

This section is maintained by `tools/sync-qmt-research.ps1`.
<!-- sync-status:end -->
"@
$statusBlock = $statusBlock.TrimEnd("`r", "`n")
$readmePath = Join-Path $researchRoot 'README.md'
$readme = Get-Content -LiteralPath $readmePath -Raw
$readme = [regex]::Replace($readme, '(?s)<!-- sync-status:start -->.*?<!-- sync-status:end -->\s*\z', $statusBlock)
Set-Content -LiteralPath $readmePath -Value $readme -Encoding utf8

$progress = @"
# Research progress

- Source: D:\QMT\local-data-lake
- Branch: research
- Tracked source files: $($sourceFiles.Count)
- Latest local source modification: $latestSource
- Fork main commits not in upstream: $forkOnly
- Upstream main commits not yet reviewed: $upstreamOnly

## Update policy

The task mirrors only source, documentation, scripts, and tests from the local research directory. It excludes credentials, account files, databases, cached market data, logs, and Python caches. Upstream is fetched and reported only: divergent upstream changes require a deliberate review and merge, never an automatic overwrite.
"@
if ($DryRun) {
    Write-Output $progress
    git -C $repoRoot status --short -- research
    exit 0
}

Set-Content -LiteralPath (Join-Path $researchRoot 'PROGRESS.md') -Value $progress -Encoding utf8

$changelog = @"
# Fork and research changelog

This file is generated by tools/sync-qmt-research.ps1. It records the Git-level difference between HirahPan/xtquant_big_convert and litaolemo/xtquant_big_convert; it does not replace a review before a merge.

## Current divergence

- Fork main commits not in upstream: $forkOnly
- Upstream main commits awaiting review: $upstreamOnly

## Upstream commits awaiting review

$($upstreamCommits -join "`n")

## Recent fork-only main commits

$($forkCommits -join "`n")
"@
Set-Content -LiteralPath (Join-Path $researchRoot 'CHANGELOG.md') -Value $changelog -Encoding utf8

git -C $repoRoot add -- research tools/sync-qmt-research.ps1 tools/sync-upstream-main.ps1
if ($LASTEXITCODE -ne 0) { throw 'Staging research changes failed.' }
$staged = git -C $repoRoot diff --cached --quiet
if ($LASTEXITCODE -eq 0) {
    Write-Output 'No research changes to commit.'
    exit 0
}

git -C $repoRoot commit -m "research: sync local data-lake"
if ($LASTEXITCODE -ne 0) { throw 'Commit failed; refusing to push an incomplete sync.' }
git -C $repoRoot push --set-upstream origin research
if ($LASTEXITCODE -ne 0) { throw 'Push failed; the local research commit remains available for retry.' }
